name: release

on: 
  push:
    tags:
      - release-*

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  build_test_publish:
    name: "init → build → deploy → invalidate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: init
        run: |
          make init
          
      - name: build
        run: |
          make build
      
      - name: deploy
        run: |
          make deploy

      - name: invalidate
        run: |
          make invalidate
